using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("1.3.1")]
[assembly: AssemblyFileVersionAttribute("1.3.1")]
[assembly: AssemblyTitleAttribute("com.mosso.cloudfiles")]
[assembly: AssemblyDescriptionAttribute("C#.NET API for Rackspace Cloud Files Cloud Storage")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2008 2009, Rackspace Managed Hosting")]
[assembly: AssemblyCompanyAttribute("Rackspace Managed Hosting")]

